#!/bin/bash
# Unified script to regenerate auto-generated CLI documentation
# Usage: ./scripts/update_cli_docs_unified.sh <cli_name> [target_version]
#
# Examples:
#   ./scripts/update_cli_docs_unified.sh aztec                    # Updates aztec CLI, all versions
#   ./scripts/update_cli_docs_unified.sh aztec-wallet current     # Updates aztec-wallet CLI, current only
#   ./scripts/update_cli_docs_unified.sh aztec v2.0.2             # Updates aztec CLI, v2.0.2 only

set -euo pipefail  # Added 'u' for undefined variable check, 'o pipefail' for pipe failures

# Validate arguments
if [[ $# -lt 1 ]]; then
  echo "Error: CLI name is required"
  echo "Usage: $0 <cli_name> [target_version]"
  echo "  cli_name: 'aztec' or 'aztec-wallet'"
  echo "  target_version: 'all' (default), 'current', or version like 'v2.0.2'"
  exit 1
fi

CLI_NAME="$1"
TARGET_VERSION="${2:-all}"

# Validate CLI name
if [[ "$CLI_NAME" != "aztec" && "$CLI_NAME" != "aztec-wallet" ]]; then
  echo "Error: Invalid CLI name '$CLI_NAME'. Must be 'aztec' or 'aztec-wallet'"
  exit 1
fi

# Constants
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DOCS_ROOT="$(cd "$SCRIPT_DIR/.." && pwd)"
readonly SCRIPT_DIR DOCS_ROOT TARGET_VERSION CLI_NAME

# Configuration per CLI (compatible with bash 3.2+)
case "$CLI_NAME" in
  aztec)
    DISPLAY_NAME="Aztec CLI"
    TITLE="Aztec CLI Reference"
    OUTPUT_FILE="cli_reference_autogen.md"
    SIDEBAR_POSITION="2"
    MANUAL_REF_FILE="./cli_reference.md"
    COMMAND="aztec"
    ;;
  aztec-wallet)
    DISPLAY_NAME="Aztec Wallet CLI"
    TITLE="Aztec Wallet CLI Reference"
    OUTPUT_FILE="cli_wallet_reference_autogen.md"
    SIDEBAR_POSITION="3"
    MANUAL_REF_FILE="./cli_wallet_reference.md"
    COMMAND="aztec-wallet"
    ;;
esac

echo "=== ${DISPLAY_NAME} Documentation Update Script ==="
echo ""

# Step 1: Generate JSON from CLI
echo "Step 1: Scanning ${COMMAND} CLI commands..."
readonly TEMP_JSON="/tmp/${CLI_NAME//-/_}_cli_docs_$(date +%s).json"
python3 "$SCRIPT_DIR/generate_cli_docs.py" --command "$COMMAND" --output "$TEMP_JSON"

# Step 2: Generate markdown
echo ""
echo "Step 2: Generating markdown documentation..."
readonly TEMP_MD="/tmp/${CLI_NAME//-/_}_cli_auto_$(date +%s).md"
python3 "$SCRIPT_DIR/transform_cli_docs.py" \
  --input "$TEMP_JSON" \
  --output "$TEMP_MD" \
  --title "$TITLE"

# Step 3: Add front-matter
readonly TEMP_WITH_FRONTMATTER="/tmp/${CLI_NAME//-/_}_cli_final_$(date +%s).md"

# Determine tags based on CLI
TAGS="[cli, reference, autogenerated"
[[ "$CLI_NAME" == "aztec-wallet" ]] && TAGS+=", wallet"
TAGS+="]"

cat > "$TEMP_WITH_FRONTMATTER" << EOF
---
title: ${TITLE} (Auto-generated)
description: Comprehensive auto-generated reference for the ${DISPLAY_NAME} command-line interface with all commands and options.
tags: ${TAGS}
sidebar_position: ${SIDEBAR_POSITION}
---

# ${TITLE}

*This documentation is auto-generated from the \`${COMMAND}\` CLI help output.*

:::info
This is an auto-generated reference. For a more curated guide with examples and best practices, see the [manual ${DISPLAY_NAME} reference](${MANUAL_REF_FILE}).
:::

EOF

# Append markdown content (skip first line which is duplicate title)
tail -n +2 "$TEMP_MD" >> "$TEMP_WITH_FRONTMATTER"

# Step 4: Deploy to target locations
echo ""
echo "Step 3: Deploying documentation..."

update_version() {
  local version=$1
  local target_dir=""

  if [[ "$version" == "current" ]]; then
    target_dir="$DOCS_ROOT/docs/developers/docs/reference/environment_reference"
  else
    target_dir="$DOCS_ROOT/versioned_docs/version-${version}/developers/docs/reference/environment_reference"
  fi

  if [[ ! -d "$target_dir" ]]; then
    echo "  Warning: Directory not found: $target_dir"
    return 1
  fi

  cp "$TEMP_WITH_FRONTMATTER" "$target_dir/$OUTPUT_FILE"
  echo "  ✓ Updated $version"
  return 0
}

case "$TARGET_VERSION" in
  all)
    # Update main docs
    update_version "current" || true

    # Update all versioned docs
    if [[ -f "$DOCS_ROOT/versions.json" ]]; then
      # Use jq if available for robust JSON parsing, otherwise fallback to grep
      if command -v jq &> /dev/null; then
        versions=$(jq -r '.[]' "$DOCS_ROOT/versions.json")
      else
        versions=$(grep -o '"v[^"]*"' "$DOCS_ROOT/versions.json" | tr -d '"')
      fi

      for version in $versions; do
        update_version "$version" || true
      done
    fi
    ;;
  current)
    update_version "current"
    ;;
  *)
    update_version "$TARGET_VERSION"
    ;;
esac

# Cleanup
rm -f "$TEMP_JSON" "$TEMP_MD" "$TEMP_WITH_FRONTMATTER"

echo ""
echo "=== Documentation Update Complete ==="
echo ""
echo "Files updated with auto-generated ${DISPLAY_NAME} reference."
echo "You can now commit these changes to the repository."
